namespace Discord
{
    public enum DiscordError
    {
        UnknownAccount = 10001,
        UnknownApp,
        UnknownChannel,
        UnknownGuild,
        UnknownIntegration,
        UnknownInvite,
        UnknownMember,
        UnknownMessage,
        UnknownOverwrite,
        UnknownProvider,
        UnknownRole,
        UnknownAuthAppToken,
        UnknownUser,
        UnknownEmoji,
        UnknownWebhook,
        UnknownGiftCode = 10038,
        UnknownGuildSubscriptionCooldown = 10050,
        UserOnly = 20001,
        BotOnly,
        MaximumGuilds = 30001,
        MaximumFriends,
        MaximumPins,
        MaximumRoles,
        MaximumConnections = 30009,
        MaximumReactions = 30010,
        MaximumGuildChannels = 30013,
        MaximumGuildSubscriptions = 30026,
        Unauthorized = 40001,
        AccountUnverified,
        InvalidInvite = 40007,
        AccountOwnsGuilds = 40011,
        NotConnectedToVoice = 40032,
        MissingAccess = 50001,
        InvalidAccountType,
        CannotExecuteInDM,
        WidgetDisabled,
        CannotEditMessageByOtherUser,
        CannotSendEmptyMessage,
        CannotDMThisUser,
        CannotSendMessagesInVC,
        ChannelVerificationTooHigh,
        OAuth2AppDoesNotHaveABot,
        OAuth2AppLimitReached,
        InvalidOAuthState,
        MissingPermissions,
        InvalidAuthToken,
        NoteTooLong,
        InvalidBulkDeleteAmount,
        PasswordDoesNotMatch = 50018,
        CannotPinMessageInOtherChannel = 50019,
        InvalidPhoneNumber = 50022,
        CannotExecuteOnSysMessage = 50025,
        InvalidRecipient = 50033,
        InvalidOAuthAccessToken = 50034,
        InvalidFormBody,
        InvalidAPIVersion = 50041,
        NitroGiftRedeemed = 50050,
        InvalidGuild = 50055,
        GuildSubscriptionCooldown = 50069,
        IncomingFriendRequestsDisabled = 80000,
        InvalidDiscriminator = 80004,
        ReactionBlocked = 90001,
        ResourceOverloaded = 130000
    }
}
